BUG: Fix DWI shell extraction module import sorting
SlicerDMRI/SlicerDMRI pull request #202
Opened 2023-11-04 14:24 UTC by jhlegarreta

Fix DWI shell extraction module import sorting: sort the imported packages following the class hierarchy and library dependencies.

Fixes:
```
loading:  /SlicerDMRI/SlicerDMRI/Testdata/3x3x3_13_b1000_b3000.nrrd
Traceback (most recent call last):
  File "/SlicerDMRI-build/inner-build/lib/Slicer-5.5/cli-modules/ExtractDWIShells.py",
  line 207, in <module>
    main()
  File "/SlicerDMRI-build/inner-build/lib/Slicer-5.5/cli-modules/ExtractDWIShells.py",
  line 127, in main
    sn.ReadData(node_in)
TypeError: ReadData argument 1: method requires a VTK object
```

raised for example at:
https://github.com/SlicerDMRI/SlicerDMRI/actions/runs/6722459285/job/18270424711?pr=191#step:8:2631

Related discussion:
https://github.com/Slicer/Slicer/issues/6484

2023-11-05 14:00 UTC, jhlegarreta commented
Rebase on `master` after PR #191 gets merged to demonstrate that the patch set fixes the issue.

2023-11-16 06:46 UTC, jcfr requested changes
Instead of fixing the ordering on a few files, the complete code base should be updated using tooling like `Ruff`.

To help with this, you may look at this  pull request where I introduced the use of Ruff:
* https://github.com/mazurowski-lab/SlicerSegmentWithSAM/pull/8

Additionally, a GitHub workflow for running `pre-commit` should be added.

2023-11-16 15:42 UTC, jhlegarreta commented
@jcfr this PR does not aim at fixing the style of imports; it aims at fixing the test. The fix was applied after reading https://github.com/Slicer/Slicer/issues/6484#issuecomment-1198453570, and Steve had also mentioned the import sorting in https://discourse.slicer.org/t/fixing-extension-testing-failures/32584/2

Applying `Ruff` would change virtually all files in the repository, and before doing that, first is to have the tests passing.

I ignore how `Ruff` deals with the import sorting, but note that before `Ruff` was adopted by 3D Slicer on Nov 3 https://github.com/Slicer/Slicer/pull/7338, I had submitted PRs #186, #187 and #188 to SlicerDMRI late October. Note that `isort` would sort imports alphabetically (unless an explicit exclusion statement is added to the import line to tell `isort` not to apply its rules). Alphabetical sorting is clear and consistent, and easy to follow when reading code. However, following the above posts, 3D Slicer seems to require manually sorting some of the imports.  As a side note, this 3D Slicer PR is relevant to the discussion https://github.com/Slicer/Slicer/pull/6613, as well as this comment https://github.com/Slicer/Slicer/pull/6613#issuecomment-1287482114.

So, please, @jcfr consider the scope of the PR and re-consider the review.

2023-11-16 23:15 UTC, jcfr commented
> consider the scope of the PR and re-consider the review.

Thanks for clarifying.

Since adjusting the order of the import is prone to error, I addressed the issue in Slicer itself. This change is superseded by:
* https://github.com/Slicer/Slicer/pull/7402

2023-11-16 23:20 UTC, jhlegarreta commented
> Since adjusting the order of the import is prone to error, I addressed the issue in Slicer itself. This change is superseded by:
> * https://github.com/Slicer/Slicer/pull/7402

:+1: hats off to the PR in 3D Slicer. Thank you.

2023-11-17 13:20 UTC, jhlegarreta commented
The `ExtractDWIShells_Test` test is passing now:
https://slicer.cdash.org/viewTest.php?onlyfailed&buildid=3212756
vs
https://slicer.cdash.org/viewTest.php?onlyfailed&buildid=3211674

Closing. Thanks @jcfr.

2023-11-17 13:20 UTC, closed without merging