BUG: Fix weakref method warning
SlicerDMRI/SlicerDMRI pull request #214
Opened 2023-11-11 22:40 UTC by jhlegarreta

Fix weakref method warning: make the callback methods be methods of the `Workflow` class.

Fixes:
```
test_widgetRepresentation
(qSlicerDICOM2FullBrainTractographyModuleGenericTest.
qSlicerDICOM2FullBrainTractographyModuleGenericTest)
... Traceback (most recent call last):
  File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractography.py",
 line 44, in setup
    self.full_tractography_workflow = DICOM2FullBrainTractographyLib.Workflow(
  File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py",
 line 82, in __init__
    step = GeneralizedStep(step_widget_file, widget,
  File "SlicerDMRI-build/inner-build/lib/Slicer-5.4/qt-scripted-modules/DICOM2FullBrainTractographyLib/workflow_support.py",
 line 135, in __init__
    self.weak_onEntryCallback = weakref.WeakMethod(onEntryCallback)
  File "python-install/lib/python3.9/weakref.py", line 52, in __new__
    raise TypeError("argument should be a bound method, not {}"
TypeError: argument should be a bound method, not <class 'function'>
```

raised for example in
https://slicer.cdash.org/test/26001793

2023-11-11 22:42 UTC, jhlegarreta commented
Alternatively, keeping the methods private and applying the below does also work
```
import types

(...)

if onEntryCallback:
    if isinstance(onEntryCallback, types.MethodType):
        self.weak_onEntryCallback = weakref.WeakMethod(onEntryCallback)
    else:
        self.weak_onEntryCallback = weakref.ref(onEntryCallback)

(...)
```

@jamesobutler I've seen a slightly related commit of yours about `weakrefs` in Slicer: https://github.com/SlicerDMRI/SlicerDMRI/pull/125

TBH, I am not sure the proposed patch should be the preferred solution. Would be grateful if you reviewed the PR. Thanks.

2023-11-16 06:57 UTC, jcfr requested changes
For reference, the function were originally introduced in 92fc1514b (COMP: Re-organize Scripted module directories).

The proposed change incorrectly associated the code expected to be executed as part of the `__init__` function to the `validateCallback` function.

2023-11-16 07:34 UTC, jcfr approved these changes
The updated patch allows the test `qSlicerDICOM2FullBrainTractographyModuleGenericTest` to pass.


<details><summary><tt>ctest -R qSlicerDICOM2FullBrainTractographyModuleGenericTest -V</tt></summary>

<pre>

$ ctest -R qSlicerDICOM2FullBrainTractographyModuleGenericTest -V 
[...]
Checking test dependency graph...
Checking test dependency graph end
test 49
    Start 49: py_nomainwindow_qSlicerDICOM2FullBrainTractographyModuleGenericTest

49: Test command: /home/jcfr/Projects/Slicer-Release/Slicer-build/Slicer "--no-splash" "--testing" "--launcher-additional-settings" "/home/jcfr/Projects/SlicerDMRI-Release/inner-build/AdditionalLauncherSettings.ini" "--no-main-window" "--disable-cli-modules" "--additional-module-path" "/home/jcfr/Projects/SlicerDMRI-Release/inner-build/lib/Slicer-5.5/qt-scripted-modules" "--additional-module-paths" "/home/jcfr/Projects/SlicerDMRI-Release/inner-build/lib/Slicer-5.5/qt-scripted-modules" "/home/jcfr/Projects/SlicerDMRI-Release/inner-build/lib/Slicer-5.5/qt-loadable-modules" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['/home/jcfr/Projects/SlicerDMRI-Release/inner-build/Modules/Scripted/DICOM2FullBrainTractography', '/home/jcfr/Projects/SlicerDMRI/Modules/Scripted/DICOM2FullBrainTractography'], 'qSlicerDICOM2FullBrainTractographyModuleGenericTest')"
49: Working Directory: /home/jcfr/Projects/SlicerDMRI-Release/inner-build/Modules/Scripted/DICOM2FullBrainTractography
49: Test timeout computed to be: 1500
49: /home/jcfr/Projects/SlicerDMRI-Release/inner-build/lib/Slicer-5.5/qt-scripted-modules/RegisterDMRIModuleTemplates.py:26: UserWarning: SlicerDMRI template module path '/home/jcfr/Projects/Slicer-Release/Slicer-build/slicer.org/Extensions-32335/SlicerDMRI/DMRIModuleTemplates' is missing.
49:                        Templates will not be auto-registered
49:   warnings.warn(textwrap.dedent(
49: When loading module  "CropVolume" , the dependency "ResampleScalarVectorDWIVolume" failed to be loaded.
49: qSlicerMarkupsModulePrivate::addToolBar: no main window is available, toolbar is not added
49: qSlicerSequencesModulePrivate::addToolBar: no main window is available, toolbar is not added
49: -------------------------------------------
49: path: ['/home/jcfr/Projects/SlicerDMRI-Release/inner-build/Modules/Scripted/DICOM2FullBrainTractography', '/home/jcfr/Projects/SlicerDMRI/Modules/Scripted/DICOM2FullBrainTractography']
49: testname: qSlicerDICOM2FullBrainTractographyModuleGenericTest
49: -------------------------------------------
49: test_acknowledgementText (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_application (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_categories (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_contributors (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_file_attribute (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_logic (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_module_valid (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_name_attribute (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_setCurrentModule (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_setMRMLScene (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_settings (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: test_widgetRepresentation (qSlicerDICOM2FullBrainTractographyModuleGenericTest.qSlicerDICOM2FullBrainTractographyModuleGenericTest) ... ok
49: 
49: ----------------------------------------------------------------------
49: Ran 12 tests in 0.212s
49: 
49: OK
1/1 Test #49: py_nomainwindow_qSlicerDICOM2FullBrainTractographyModuleGenericTest ...   Passed    4.11 sec

The following tests passed:
	py_nomainwindow_qSlicerDICOM2FullBrainTractographyModuleGenericTest

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   4.11 sec


</pre>

</details>

After locally adding the following patch  ....

```diff
diff --git a/Modules/Scripted/DICOM2FullBrainTractography/DICOM2FullBrainTractographyLib/workflow_support.py b/Modules/Scripted/DICOM2FullBrainTractography/DICOM2FullBrainTractographyLib/workflow_support.py
index 7bfa86a..5e6adfa 100644
--- a/Modules/Scripted/DICOM2FullBrainTractography/DICOM2FullBrainTractographyLib/workflow_support.py
+++ b/Modules/Scripted/DICOM2FullBrainTractography/DICOM2FullBrainTractographyLib/workflow_support.py
@@ -28,6 +28,8 @@ class Workflow(object):
 
         self.steps = []
 
+        print(f"Workflow init self {self}")
+
         for step_widget_file in self.workflow_configuration.step_widget_files:
             path = os.path.join(
                  os.path.dirname(__file__), 'Resources', 'UI',
@@ -66,6 +68,7 @@ class Workflow(object):
 
 
     def onEntryCallback(self, actual_step, comingFrom, transitionType):
+        print(f"Workflow onEntryCallback self {self}")
         data = self.extract_data()
 
         method_name = 'on_entry_'+actual_step.id()
@@ -126,6 +129,7 @@ class GeneralizedStep(ctk.ctkWorkflowWidgetStep, ) :
         self.initialize(stepid)
         self.qt_widget = qt_widget
 
+        print(f"GeneralizedStep init self {self}")
         if onEntryCallback:
             self.weak_onEntryCallback = weakref.WeakMethod(onEntryCallback)
```

I also confirmed that the `self` value within the callback is the correct one:

```
$ ctest -R qSlicerDICOM2FullBrainTractographyModuleGenericTest -V 
[...]
49: Workflow init self <DICOM2FullBrainTractographyLib.workflow_support.Workflow object at 0x7f6489fca8b0>
49: GeneralizedStep init self ctkWorkflowWidgetStep(0x55ebf5b255a0) 
49: GeneralizedStep init self ctkWorkflowWidgetStep(0x55ebf5b4cf80) 
49: GeneralizedStep init self ctkWorkflowWidgetStep(0x55ebf5b3a7c0) 
49: GeneralizedStep init self ctkWorkflowWidgetStep(0x55ebf5b2f870) 
49: Workflow onEntryCallback self <DICOM2FullBrainTractographyLib.workflow_support.Workflow object at 0x7f6489fca8b0>

[...]
The following tests passed:
	py_nomainwindow_qSlicerDICOM2FullBrainTractographyModuleGenericTest

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   4.13 sec
```

Indeed, in this example, both `Workflow init self` and `Workflow onEntryCallback self` are associated with `0x7f6489fca8b0`

2023-11-30 15:26 UTC, ljod approved these changes

2023-11-30 15:26 UTC, merged